name: default
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Tests
        run:  go test -v ./...
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Build
        run: |
          gitTag=$(git branch | grep \* | cut -d ' ' -f2)
          GOOS=linux GOARCH=amd64 make build RELEASE=$gitTag OUTPUT=cataloger_darwin_amd64
          GOOS=linux GOARCH=amd64 make build RELEASE=$gitTag OUTPUT=cataloger_linux_amd64
          
      - uses: actions/upload-artifact@master
        with:
          name: cataloger_darwin_amd64
          path: cataloger_darwin_amd64
      
      - uses: actions/upload-artifact@master
        with:
          name: cataloger_linux_amd64
          path: cataloger_linux_amd64