name: default
on: 
  push:
    branches:    
      - master
      - 'feature/**'
      - 'fix/**'
    paths-ignore:
      - README.md
    tags-ignore:
      - v*
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Tests
        run:  go test -v ./...

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 make build RELEASE=${GITHUB_REF##*/} BINARY_NAME=cataloger_darwin_amd64
          GOOS=linux GOARCH=amd64 make build RELEASE=${GITHUB_REF##*/} BINARY_NAME=cataloger_linux_amd64
