name: release
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Tests
        run:  go test -v ./...

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 make build RELEASE=${GITHUB_REF##*/} BINARY_NAME=cataloger_darwin_amd64
          GOOS=linux GOARCH=amd64 make build RELEASE=${GITHUB_REF##*/} BINARY_NAME=cataloger_linux_amd64
          
      - uses: actions/upload-artifact@master
        with:
          name: cataloger_darwin_amd64
          path: cataloger_darwin_amd64
      
      - uses: actions/upload-artifact@master
        with:
          name: cataloger_linux_amd64
          path: cataloger_linux_amd64