name: release
on: release
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Tests
        run:  go test -v ./...
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, centos-7]
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Build
        run: |
          gitTag = $(git describe --tags)
          make build RELEASE=$gitTag OUTPUT=cataloger

      - uses: actions/upload-artifact@master
        with:
          name: cataloger
          path: cataloger