name: release
on: 
  push:
    tags:        
      - v.*
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Tests
        run:  go test -v ./...

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 make build RELEASE=${GITHUB_REF##*/} OUTPUT=cataloger_darwin_amd64
          GOOS=linux GOARCH=amd64 make build RELEASE=${GITHUB_REF##*/} OUTPUT=cataloger_linux_amd64
      
      - uses: actions/upload-artifact@master
        with:
          name: cataloger_${{ steps.get_version.outputs.VERSION }}_darwin_amd64
          path: cataloger_darwin_amd64
      
      - uses: actions/upload-artifact@master
        with:
          name: cataloger_${{ steps.get_version.outputs.VERSION }}_linux_amd64
          path: cataloger_linux_amd64